# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/xaviersavoie/StagingPro/GameProjectServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/xaviersavoie/StagingPro/GameProjectServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xaviersavoie/StagingPro/GameProjectServer/CMakeFiles /Users/xaviersavoie/StagingPro/GameProjectServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xaviersavoie/StagingPro/GameProjectServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/xaviersavoie/StagingPro/GameProjectServer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

# target to build an object file
src/Chunk.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Chunk.o
.PHONY : src/Chunk.o

# target to preprocess a source file
src/Chunk.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Chunk.i
.PHONY : src/Chunk.i

# target to generate assembly for a file
src/Chunk.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Chunk.s
.PHONY : src/Chunk.s

# target to build an object file
src/ClientEntityPositionPacket.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ClientEntityPositionPacket.o
.PHONY : src/ClientEntityPositionPacket.o

# target to preprocess a source file
src/ClientEntityPositionPacket.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ClientEntityPositionPacket.i
.PHONY : src/ClientEntityPositionPacket.i

# target to generate assembly for a file
src/ClientEntityPositionPacket.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ClientEntityPositionPacket.s
.PHONY : src/ClientEntityPositionPacket.s

# target to build an object file
src/Entity.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Entity.o
.PHONY : src/Entity.o

# target to preprocess a source file
src/Entity.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Entity.i
.PHONY : src/Entity.i

# target to generate assembly for a file
src/Entity.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Entity.s
.PHONY : src/Entity.s

# target to build an object file
src/Game.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Game.o
.PHONY : src/Game.o

# target to preprocess a source file
src/Game.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Game.i
.PHONY : src/Game.i

# target to generate assembly for a file
src/Game.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Game.s
.PHONY : src/Game.s

# target to build an object file
src/PacketManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PacketManager.o
.PHONY : src/PacketManager.o

# target to preprocess a source file
src/PacketManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PacketManager.i
.PHONY : src/PacketManager.i

# target to generate assembly for a file
src/PacketManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PacketManager.s
.PHONY : src/PacketManager.s

# target to build an object file
src/Parser.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Parser.o
.PHONY : src/Parser.o

# target to preprocess a source file
src/Parser.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Parser.i
.PHONY : src/Parser.i

# target to generate assembly for a file
src/Parser.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Parser.s
.PHONY : src/Parser.s

# target to build an object file
src/Perlin3D.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Perlin3D.o
.PHONY : src/Perlin3D.o

# target to preprocess a source file
src/Perlin3D.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Perlin3D.i
.PHONY : src/Perlin3D.i

# target to generate assembly for a file
src/Perlin3D.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Perlin3D.s
.PHONY : src/Perlin3D.s

# target to build an object file
src/TCPConnection.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPConnection.o
.PHONY : src/TCPConnection.o

# target to preprocess a source file
src/TCPConnection.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPConnection.i
.PHONY : src/TCPConnection.i

# target to generate assembly for a file
src/TCPConnection.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPConnection.s
.PHONY : src/TCPConnection.s

# target to build an object file
src/TCPServer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPServer.o
.PHONY : src/TCPServer.o

# target to preprocess a source file
src/TCPServer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPServer.i
.PHONY : src/TCPServer.i

# target to generate assembly for a file
src/TCPServer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TCPServer.s
.PHONY : src/TCPServer.s

# target to build an object file
src/Vec3d.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Vec3d.o
.PHONY : src/Vec3d.o

# target to preprocess a source file
src/Vec3d.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Vec3d.i
.PHONY : src/Vec3d.i

# target to generate assembly for a file
src/Vec3d.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Vec3d.s
.PHONY : src/Vec3d.s

# target to build an object file
src/Voxel.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Voxel.o
.PHONY : src/Voxel.o

# target to preprocess a source file
src/Voxel.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Voxel.i
.PHONY : src/Voxel.i

# target to generate assembly for a file
src/Voxel.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Voxel.s
.PHONY : src/Voxel.s

# target to build an object file
src/VoxelAir.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelAir.o
.PHONY : src/VoxelAir.o

# target to preprocess a source file
src/VoxelAir.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelAir.i
.PHONY : src/VoxelAir.i

# target to generate assembly for a file
src/VoxelAir.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelAir.s
.PHONY : src/VoxelAir.s

# target to build an object file
src/VoxelDirt.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelDirt.o
.PHONY : src/VoxelDirt.o

# target to preprocess a source file
src/VoxelDirt.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelDirt.i
.PHONY : src/VoxelDirt.i

# target to generate assembly for a file
src/VoxelDirt.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelDirt.s
.PHONY : src/VoxelDirt.s

# target to build an object file
src/VoxelJohan.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelJohan.o
.PHONY : src/VoxelJohan.o

# target to preprocess a source file
src/VoxelJohan.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelJohan.i
.PHONY : src/VoxelJohan.i

# target to generate assembly for a file
src/VoxelJohan.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/VoxelJohan.s
.PHONY : src/VoxelJohan.s

# target to build an object file
src/WorldServer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/WorldServer.o
.PHONY : src/WorldServer.o

# target to preprocess a source file
src/WorldServer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/WorldServer.i
.PHONY : src/WorldServer.i

# target to generate assembly for a file
src/WorldServer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/WorldServer.s
.PHONY : src/WorldServer.s

# target to build an object file
src/main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/main.s
.PHONY : src/main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Main"
	@echo "... src/Chunk.o"
	@echo "... src/Chunk.i"
	@echo "... src/Chunk.s"
	@echo "... src/ClientEntityPositionPacket.o"
	@echo "... src/ClientEntityPositionPacket.i"
	@echo "... src/ClientEntityPositionPacket.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/PacketManager.o"
	@echo "... src/PacketManager.i"
	@echo "... src/PacketManager.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Perlin3D.o"
	@echo "... src/Perlin3D.i"
	@echo "... src/Perlin3D.s"
	@echo "... src/TCPConnection.o"
	@echo "... src/TCPConnection.i"
	@echo "... src/TCPConnection.s"
	@echo "... src/TCPServer.o"
	@echo "... src/TCPServer.i"
	@echo "... src/TCPServer.s"
	@echo "... src/Vec3d.o"
	@echo "... src/Vec3d.i"
	@echo "... src/Vec3d.s"
	@echo "... src/Voxel.o"
	@echo "... src/Voxel.i"
	@echo "... src/Voxel.s"
	@echo "... src/VoxelAir.o"
	@echo "... src/VoxelAir.i"
	@echo "... src/VoxelAir.s"
	@echo "... src/VoxelDirt.o"
	@echo "... src/VoxelDirt.i"
	@echo "... src/VoxelDirt.s"
	@echo "... src/VoxelJohan.o"
	@echo "... src/VoxelJohan.i"
	@echo "... src/VoxelJohan.s"
	@echo "... src/WorldServer.o"
	@echo "... src/WorldServer.i"
	@echo "... src/WorldServer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/xaviersavoie/StagingPro/GameProjectServer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

